/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings` (hash: 48af281bf069ced81ee7edf099bce5e4)
interface __BaseEnv_CloudflareBindings {
	GEMINI_MODEL: string;
	GOOGLE_WEB_CLIENT_ID: string;
	APPLE_BUNDLE_ID: string;
	ALLOWED_ORIGINS: string;
	SCANS_ENABLED: string;
	USER_REQUESTS_PER_MINUTE: string;
	IP_REQUESTS_PER_MINUTE: string;
	USER_SCANS_PER_MONTH: string;
	IP_SCANS_PER_DAY: string;
	INPUT_USD_PER_MILLION: string;
	OUTPUT_USD_PER_MILLION: string;
	SCAN_GUARD: DurableObjectNamespace /* ScanGuard */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GEMINI_MODEL" | "GOOGLE_WEB_CLIENT_ID" | "APPLE_BUNDLE_ID" | "ALLOWED_ORIGINS" | "SCANS_ENABLED" | "USER_REQUESTS_PER_MINUTE" | "IP_REQUESTS_PER_MINUTE" | "USER_SCANS_PER_MONTH" | "IP_SCANS_PER_DAY" | "INPUT_USD_PER_MILLION" | "OUTPUT_USD_PER_MILLION">> {}
}
